const MIND_URL='https://dabzmzwnvzoeywyflkoo.supabase.co/functions/v1/mind';
const BANK_URL='https://dabzmzwnvzoeywyflkoo.supabase.co/functions/v1/bank';
const TOKEN_KEY='sm_device_token',CACHE_KEY='sm_capture_cache_v3',QUEUE_KEY='sm_pending_captures_v3';
const state={captures:[],aiEnabled:false,filter:'all',query:'',loading:true,listening:false,bank:null,bankLoading:false};
let recognition=null,toastTimer=null,currentView='hoy',freshId=null,lastRefresh=0;
const $=id=>document.getElementById(id);
const token=()=>localStorage.getItem(TOKEN_KEY)||'';
const readJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const writeJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const euro=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(Number(n)||0);
const dateFmt=new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}),timeFmt=new Intl.DateTimeFormat('es-ES',{hour:'2-digit',minute:'2-digit'});
const safeDate=v=>{const d=new Date(v);return Number.isFinite(d.getTime())?d:null};
const createdLabel=t=>{const d=safeDate(t);return d?`${dateFmt.format(d)} · ${timeFmt.format(d)}`:'Ahora'};
const dueLabel=t=>{const d=safeDate(t);if(!d)return'';const today=new Date(),tom=new Date();tom.setDate(today.getDate()+1);const same=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();return `${same(d,today)?'Hoy':same(d,tom)?'Mañana':dateFmt.format(d)} · ${timeFmt.format(d)}`};
const typeLabel=k=>({task:'Tarea',event:'Plan',idea:'Idea',expense:'Gasto',income:'Ingreso',debt:'Pendiente',note:'Nota'})[k]||'Nota';
const icon=kind=>{const paths={task:'<path d="M5 12.5 9.2 17 19 7"/><path d="M4 4h16v16H4z"/>',event:'<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/>',idea:'<path d="M9 18h6M10 21h4"/><path d="M8.2 14.5A6 6 0 1 1 16 14c-.9.8-1.5 1.7-1.7 2.5h-4.6c-.2-.7-.7-1.4-1.5-2Z"/>',expense:'<path d="M5 7h14v10H5z"/><path d="M9 10h.01M15 14h.01M12 10v4"/>',income:'<path d="M5 7h14v10H5z"/><path d="m9 13 2 2 4-5"/>',debt:'<path d="M5 8h10M12 5l3 3-3 3M19 16H9M12 13l-3 3 3 3"/>',note:'<path d="M6 4h12v16H6z"/><path d="M9 8h6M9 12h6M9 16h4"/>'};return `<svg viewBox="0 0 24 24">${paths[kind]||paths.note}</svg>`};
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.classList.remove('show'),2100)}
function queue(){return readJSON(QUEUE_KEY,[])}
function setQueue(q){writeJSON(QUEUE_KEY,q);$('queueState').textContent=String(q.length)}
function syncState(mode,label){const s=$('syncStatus'),dot=s.querySelector('.statusdot'),txt=s.querySelector('span:last-child');dot.classList.toggle('offline',mode==='offline');dot.classList.toggle('syncing',mode==='syncing');txt.textContent=label}
function setOnlineUI(){const online=navigator.onLine;syncState(online?'ok':'offline',online?'Sincronizada':'Sin conexión');$('offlineBanner').classList.toggle('show',!online)}
async function bankApi(body=null,method='POST',timeout=25000){const t=token();if(!t)throw new Error('no_session');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(BANK_URL,{method,signal:controller.signal,headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.detail||out.error||'bank_request_failed');return out}finally{clearTimeout(timer)}}
async function loadBank({force=false,quiet=true}={}){if(state.bankLoading)return;state.bankLoading=true;try{const out=await bankApi({action:'sync',force});state.bank=out.bank||null;render();if(force&&!quiet)toast('Banco actualizado')}catch(e){try{const out=await bankApi(null,'GET',12000);state.bank=out.bank||null;render()}catch{}if(force&&!quiet)toast('No pude actualizar el banco')}finally{state.bankLoading=false}}
async function api(method='GET',body=null,timeout=12000){const t=token();if(!t){location.replace('./activar-notificaciones.html');throw new Error('no_session')}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(MIND_URL,{method,signal:controller.signal,headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(r.status===401){localStorage.removeItem(TOKEN_KEY);location.replace('./activar-notificaciones.html');throw new Error('session_expired')}const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.detail||out.error||'request_failed');return out}finally{clearTimeout(timer)}}
function useCache(){const cached=readJSON(CACHE_KEY,[]);if(Array.isArray(cached)&&cached.length){state.captures=cached;state.loading=false;render()}}
async function load({quiet=false}={}){if(!quiet)syncState('syncing','Actualizando');try{const out=await api();state.captures=out.captures||[];state.aiEnabled=!!out.aiEnabled;state.loading=false;lastRefresh=Date.now();writeJSON(CACHE_KEY,state.captures);render();updateSettings();setOnlineUI();await flushQueue()}catch(e){if(e.message!=='no_session'&&e.message!=='session_expired'){state.loading=false;render();setOnlineUI();if(!quiet)toast('Usando lo último guardado')}}finally{setTimeout(()=>$('boot').classList.add('hide'),120)}}
function go(id,{focusComposer=false}={}){if(id===currentView){if(focusComposer)$('captureText').focus({preventScroll:true});return}document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav button').forEach(b=>{const active=b.dataset.view===id;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});currentView=id;captureMotion();window.scrollTo({top:0,behavior:'auto'});if(id==='mente'&&focusComposer)setTimeout(()=>$('captureText').focus({preventScroll:true}),170)}
function captureMotion(){const st=$('captureStage');st.classList.toggle('running',currentView==='mente'&&!document.hidden)}
function metaLine(c){const parts=[];if(c.due_at)parts.push(dueLabel(c.due_at));else parts.push(createdLabel(c.created_at));if(c.category)parts.push(c.category);if(c.metadata?.pending)parts.push('por sincronizar');return parts.filter(Boolean).join(' · ')}
function rowSide(c){if((c.kind==='expense'||c.kind==='income'||c.kind==='debt')&&c.amount!=null){const sign=c.kind==='expense'?'−':c.kind==='income'?'+':'';return{text:`${sign}${euro(Math.abs(Number(c.amount)))}`,cls:c.kind==='expense'?'negative':c.kind==='income'?'positive':''}}if(c.kind==='event'&&c.due_at)return{text:dueLabel(c.due_at).split(' · ')[0],cls:''};return{text:typeLabel(c.kind),cls:''}}
function row(c,{archive=true}={}){const done=!!c.completed_at,side=rowSide(c),pending=!!c.metadata?.pending,kindClass=(c.kind==='event'||c.kind==='debt')?` ${c.kind}`:'';return `<div class="row ${done?'done':''} ${pending?'pending-sync':''}" data-id="${esc(c.id)}">${c.kind==='task'?`<button class="check press" data-complete="${esc(c.id)}" aria-label="${done?'Reabrir':'Completar'}"><svg viewBox="0 0 24 24"><path d="m5 12 4 4 10-10"/></svg></button>`:`<div class="row-icon${kindClass}">${icon(c.kind)}</div>`}<div class="row-copy"><div class="row-title">${esc(c.title||c.raw_text)}</div><div class="row-sub">${esc(metaLine(c))}</div></div><div class="row-side ${side.cls}">${esc(side.text)}</div>${archive?`<button class="correct-action press" data-correct="${esc(c.id)}" aria-label="Corregir">Corregir</button>`:''}${archive?`<button class="archive-action press" data-archive="${esc(c.id)}" aria-label="Archivar"><svg viewBox="0 0 24 24"><path d="M4 7h16v13H4zM3 3h18v5H3z"/><path d="M9 12h6"/></svg></button>`:''}</div>`}
function agendaSort(a,b){const at=a.due_at?new Date(a.due_at).getTime():Number.MAX_SAFE_INTEGER,bt=b.due_at?new Date(b.due_at).getTime():Number.MAX_SAFE_INTEGER;return at-bt||new Date(b.created_at)-new Date(a.created_at)}
function render(){const active=state.captures.filter(c=>!c.archived_at),agenda=active.filter(c=>(c.kind==='task'&&!c.completed_at)||c.kind==='event').sort(agendaSort),focus=agenda[0];$('focusTitle').textContent=focus?.title||focus?.raw_text||'Nada urgente.';$('focusMeta').textContent=focus?(focus.due_at?`${typeLabel(focus.kind)} · ${dueLabel(focus.due_at)}`:`${typeLabel(focus.kind)} · sin hora marcada`):'Tu mente está despejada.';$('todayAgenda').innerHTML=state.loading?'<div class="skeleton"></div><div class="skeleton"></div>':agenda.length?agenda.slice(0,5).map(c=>row(c,{archive:false})).join(''):'<div class="empty"><strong>Sin nada pendiente.</strong>Lo siguiente que apuntes con fecha o como tarea aparecerá aquí.</div>';$('todayRecent').innerHTML=state.loading?'<div class="skeleton"></div>':active.length?row(active[0],{archive:false}):'<div class="empty">Aún no has guardado nada.</div>';$('mindRecent').innerHTML=active.length?active.slice(0,3).map(c=>row(c,{archive:false})).join(''):'<div class="empty">Lo siguiente que captures aparecerá aquí.</div>';const now=new Date(),month=now.getMonth(),year=now.getFullYear(),money=active.filter(c=>['expense','income'].includes(c.kind)&&c.amount!=null&&new Date(c.created_at).getMonth()===month&&new Date(c.created_at).getFullYear()===year),capturedIn=money.filter(c=>c.kind==='income').reduce((s,c)=>s+Number(c.amount),0),capturedOut=money.filter(c=>c.kind==='expense').reduce((s,c)=>s+Number(c.amount),0),debts=active.filter(c=>c.kind==='debt'&&c.amount!=null),receivable=debts.filter(c=>c.metadata?.debt_direction==='receivable'||c.category==='Por cobrar').reduce((s,c)=>s+Number(c.amount),0),payable=debts.filter(c=>c.metadata?.debt_direction==='payable'||c.category==='Por pagar').reduce((s,c)=>s+Number(c.amount),0);
const bankConnected=state.bank?.connection?.status==='AUTHORIZED',bankAccounts=state.bank?.accounts||[],bankTx=state.bank?.transactions||[],bankBalance=bankAccounts.reduce((s,a)=>s+(a.current_balance==null?0:Number(a.current_balance)||0),0),hasBankBalance=bankAccounts.some(a=>a.current_balance!=null),monthBank=bankTx.filter(t=>{const d=safeDate(t.booked_at);return d&&d.getMonth()===month&&d.getFullYear()===year}),bankIn=monthBank.filter(t=>Number(t.amount)>0).reduce((s,t)=>s+Number(t.amount),0),bankOut=Math.abs(monthBank.filter(t=>Number(t.amount)<0).reduce((s,t)=>s+Number(t.amount),0));
$('moneyNet').textContent=bankConnected&&hasBankBalance?euro(bankBalance):euro(capturedIn-capturedOut);$('moneyCaption').textContent=bankConnected?(hasBankBalance?'Saldo bancario actual':'Banco conectado · saldo pendiente'):'Balance capturado este mes';$('moneyIn').textContent=euro(bankConnected?bankIn:capturedIn);$('moneyOut').textContent=euro(bankConnected?bankOut:capturedOut);$('moneyReceivable').textContent=euro(receivable);$('moneyPayable').textContent=euro(payable);
const note=$('bankNoteText');if(note)note.textContent=bankConnected?`Cajamar conectado${state.bank?.connection?.last_synced_at?' · actualizado '+new Date(state.bank.connection.last_synced_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):''}`:'La sincronización bancaria todavía no está conectada.';
const bankBtn=$('bankConnectInline');if(bankBtn)bankBtn.textContent=bankConnected?(state.bankLoading?'Actualizando banco…':'Actualizar Cajamar'):'Conectar banco desde Segunda Mente';
const bankRows=bankTx.map(t=>({id:'bank-'+t.id,kind:Number(t.amount)<0?'expense':'income',amount:Math.abs(Number(t.amount)),title:t.merchant||t.description||'Movimiento bancario',raw_text:t.description||'',created_at:t.booked_at,category:t.account_name?('Banco · '+t.account_name):'Banco',metadata:{bank:true}}));
const ledger=bankConnected?bankRows:active.filter(c=>['expense','income','debt'].includes(c.kind)&&c.amount!=null);$('moneyRows').innerHTML=ledger.length?ledger.slice(0,30).map(c=>row(c,{archive:false})).join(''):bankConnected?'<div class="empty"><strong>Banco conectado.</strong>Todavía no he recibido movimientos desde Cajamar.</div>':'<div class="empty"><strong>Sin movimientos todavía.</strong>Di “18,50 cena”, “me han pagado 400€” o “me deben 70€”.</div>';renderArchive();updateSettings();animateFresh()}
function filtered(){const q=state.query.trim().toLowerCase();return state.captures.filter(c=>!c.archived_at).filter(c=>{if(state.filter==='all')return true;if(state.filter==='money')return['expense','income'].includes(c.kind);if(state.filter==='agenda')return['task','event'].includes(c.kind);return c.kind===state.filter}).filter(c=>!q||String(c.raw_text).toLowerCase().includes(q)||String(c.title||'').toLowerCase().includes(q)||String(c.category||'').toLowerCase().includes(q))}
function renderArchive(){const items=filtered();$('archiveRows').innerHTML=items.length?items.map(c=>row(c)).join(''):'<div class="empty"><strong>Nada por aquí.</strong>Prueba otro filtro o busca con otras palabras.</div>';bindRows()}
function bindRows(){document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>complete(b.dataset.complete));document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>archiveItem(b.dataset.archive))}
function animateFresh(){if(!freshId||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const el=document.querySelector(`[data-id="${CSS.escape(freshId)}"]`);if(el)el.animate([{opacity:.25,transform:'translateY(7px)'},{opacity:1,transform:'translateY(0)'}],{duration:220,easing:'cubic-bezier(.23,1,.32,1)'});freshId=null}
async function complete(id){const c=state.captures.find(x=>x.id===id);if(!c)return;const previous=c.completed_at,next=!previous;c.completed_at=next?new Date().toISOString():null;render();try{await api('POST',{action:'complete',id,completed:next});writeJSON(CACHE_KEY,state.captures);if(next)toast('Hecho')}catch{c.completed_at=previous;render();toast('No pude sincronizar el cambio')}}
async function archiveItem(id){const c=state.captures.find(x=>x.id===id);if(!c)return;const previous=c.archived_at;c.archived_at=new Date().toISOString();render();try{await api('POST',{action:'archive',id,archived:true});writeJSON(CACHE_KEY,state.captures);toast('Apartado')}catch{c.archived_at=previous;render();toast('No pude archivarlo')}}
function localId(){return typeof crypto.randomUUID==='function'?`local-${crypto.randomUUID()}`:`local-${Date.now()}-${Math.random().toString(16).slice(2)}`}
async function saveCapture(){const el=$('captureText'),text=el.value.trim();if(!text)return toast('Escribe o di algo primero');$('captureSend').disabled=true;$('composerStatus').textContent='Guardando…';$('clarifyBox').classList.remove('show');if(!navigator.onLine){const id=localId(),q=queue();q.push({text,localId:id,createdAt:new Date().toISOString()});setQueue(q);const local={id,raw_text:text,title:text,kind:'note',amount:null,created_at:new Date().toISOString(),metadata:{pending:true}};state.captures.unshift(local);freshId=id;el.value='';writeJSON(CACHE_KEY,state.captures);render();successPulse();toast('Guardado aquí. Lo sincronizo al volver la red');$('captureSend').disabled=false;$('composerStatus').textContent='Pendiente de sincronizar';return}try{syncState('syncing','Guardando');const out=await api('POST',{action:'capture',text});state.captures.unshift(out.capture);freshId=out.capture.id;el.value='';writeJSON(CACHE_KEY,state.captures);render();successPulse();$('composerStatus').textContent=out.ai?'Entendido':'Guardado y ordenado';if(out.clarification){$('clarifyBox').textContent=out.clarification;$('clarifyBox').classList.add('show')}else toast('Guardado')}catch(e){toast(e.name==='AbortError'?'Ha tardado demasiado. Inténtalo otra vez':'No pude guardarlo');$('composerStatus').textContent='Inténtalo otra vez'}finally{$('captureSend').disabled=false;setOnlineUI()}}
async function flushQueue(){const pending=queue();if(!pending.length||!navigator.onLine)return;syncState('syncing','Sincronizando');const left=[];for(const item of pending){try{const out=await api('POST',{action:'capture',text:item.text});state.captures=state.captures.filter(c=>c.id!==item.localId);state.captures.unshift(out.capture)}catch{left.push(item)}}setQueue(left);writeJSON(CACHE_KEY,state.captures);render();setOnlineUI();if(!left.length&&pending.length)toast('Todo sincronizado')}
function successPulse(){const s=$('captureStage');s.classList.remove('success');void s.offsetWidth;s.classList.add('success');setTimeout(()=>s.classList.remove('success'),700)}
function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('captureText').focus();toast('Usa el dictado del teclado del iPhone');return}if(!recognition){recognition=new SR();recognition.lang='es-ES';recognition.interimResults=true;recognition.continuous=false;recognition.onresult=e=>{let s='';for(let i=0;i<e.results.length;i++)s+=e.results[i][0].transcript;$('captureText').value=s.trim();$('captureSend').disabled=!$('captureText').value.trim();$('composerStatus').textContent='Escuchando…'};recognition.onend=stopVoice;recognition.onerror=stopVoice}if(state.listening){recognition.stop();return}state.listening=true;$('captureStage').classList.add('listening');$('voiceHint').textContent='Te escucho…';$('composerStatus').textContent='Escuchando…';try{recognition.start()}catch{stopVoice()}}
function stopVoice(){state.listening=false;$('captureStage').classList.remove('listening');$('voiceHint').textContent='Toca el núcleo para hablar';$('composerStatus').textContent=$('captureText').value.trim()?'Listo para guardar':'Una entrada. Sin elegir carpetas.'}
function updateSettings(){$('aiState').textContent=state.aiEnabled?'Avanzada':'Local';$('aiState').classList.toggle('ok',state.aiEnabled);$('queueState').textContent=String(queue().length);if('Notification'in window){const p=Notification.permission;$('notificationState').textContent=p==='granted'?'Activas':p==='denied'?'Bloqueadas':'Sin activar';$('notificationState').classList.toggle('ok',p==='granted')}$('deviceState').textContent=token()?'Conectado':'Sin vincular';$('deviceState').classList.toggle('ok',!!token());const bs=$('bankState');if(bs){const connected=state.bank?.connection?.status==='AUTHORIZED';bs.textContent=connected?'Cajamar ✓':'Conectar →';bs.classList.toggle('ok',connected)}}
function openSheet(){$('settingsSheet').classList.add('show');$('settingsSheet').setAttribute('aria-hidden','false');document.body.classList.add('sheet-open');updateSettings();setTimeout(()=>$('sheetClose').focus({preventScroll:true}),360)}
function closeSheet(){$('settingsSheet').classList.remove('show');$('settingsSheet').setAttribute('aria-hidden','true');document.body.classList.remove('sheet-open');$('settingsBtn').focus({preventScroll:true})}
function openBankInsidePWA(){if(state.bank?.connection?.status==='AUTHORIZED'){loadBank({force:true,quiet:false});return}location.href='./conectar-banco.html'}
function init(){if(!token()){location.replace('./activar-notificaciones.html');return}$('todayDate').textContent=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date());document.querySelectorAll('.nav button').forEach(b=>{b.onclick=()=>go(b.dataset.view);if(b.dataset.view==='hoy')b.setAttribute('aria-current','page')});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(b.dataset.filter){state.filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>{const active=x.dataset.filter===state.filter;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active))})}go(b.dataset.go,{focusComposer:b.dataset.go==='mente'})});$('captureSend').onclick=saveCapture;$('voiceOrb').onclick=voice;$('quickVoice').onclick=()=>{go('mente');setTimeout(voice,180)};$('settingsBtn').onclick=openSheet;const bankSettings=$('bankSettings'),bankInline=$('bankConnectInline');if(bankSettings){bankSettings.onclick=openBankInsidePWA;bankSettings.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openBankInsidePWA()}}}if(bankInline)bankInline.onclick=openBankInsidePWA;$('sheetClose').onclick=closeSheet;$('settingsSheet').onclick=e=>{if(e.target===$('settingsSheet'))closeSheet()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('settingsSheet').classList.contains('show'))closeSheet()});$('searchInput').oninput=e=>{state.query=e.target.value;renderArchive()};document.querySelectorAll('.filter').forEach(b=>{b.setAttribute('aria-pressed',String(b.classList.contains('active')));b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active))});renderArchive()}});$('captureText').addEventListener('input',e=>{$('captureSend').disabled=!e.target.value.trim()});$('captureText').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')saveCapture()});$('captureSend').disabled=true;window.addEventListener('online',()=>{setOnlineUI();flushQueue()});window.addEventListener('offline',setOnlineUI);document.addEventListener('visibilitychange',()=>{captureMotion();if(!document.hidden&&navigator.onLine&&Date.now()-lastRefresh>15000)load({quiet:true})});setOnlineUI();captureMotion();useCache();setQueue(queue());load();setTimeout(()=>loadBank({force:false}),700);if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>reg.update?.()).catch(()=>{});/* Sin esto, un PWA ya instalado sigue sirviendo la version cacheada hasta que se cierran todas las pestanas. */let swReloaded=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(swReloaded)return;swReloaded=true;location.reload()})}}
init();
