const CACHE='segunda-mente-v3';
const STATE_CACHE='segunda-mente-state-v1';
const PUSH_MARKER='./__push_registered__';
const ASSETS=['./','./index.html','./activar-notificaciones.html','./manifest.webmanifest','./icon.svg'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting()))});
async function pushReady(){try{const sub=await self.registration.pushManager.getSubscription();if(!sub)return false;const state=await caches.open(STATE_CACHE);return !!(await state.match(PUSH_MARKER))}catch{return false}}
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE&&k!==STATE_CACHE).map(k=>caches.delete(k)));await self.clients.claim()})())});
self.addEventListener('message',event=>{if(event.data?.type==='PUSH_REGISTERED')event.waitUntil(caches.open(STATE_CACHE).then(c=>c.put(PUSH_MARKER,new Response('1',{headers:{'Content-Type':'text/plain'}}))));if(event.data?.type==='PUSH_RESET')event.waitUntil(caches.open(STATE_CACHE).then(c=>c.delete(PUSH_MARKER)))});
self.addEventListener('push',event=>{let p={title:'Segunda Mente',body:'Tienes algo pendiente.',url:'/'};if(event.data){try{p={...p,...event.data.json()}}catch{p.body=event.data.text()||p.body}}const target=new URL(p.url||'/',self.location.origin);if(target.origin!==self.location.origin)target.href=self.location.origin+'/';event.waitUntil(self.registration.showNotification(String(p.title||'Segunda Mente').slice(0,90),{body:String(p.body||'').slice(0,240),icon:'./icon.svg',data:{url:target.href},tag:p.tag?String(p.tag).slice(0,80):undefined}))});
self.addEventListener('notificationclick',event=>{event.notification.close();const target=event.notification.data?.url||self.location.origin+'/';event.waitUntil((async()=>{const windows=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of windows){if('focus'in client){try{await client.navigate(target)}catch{}return client.focus()}}return self.clients.openWindow(target)})())});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;if(req.mode==='navigate'){event.respondWith((async()=>{try{const network=await fetch(req);const copy=network.clone();caches.open(CACHE).then(c=>c.put(req,copy));return network}catch{const isRoot=url.pathname==='/'||url.pathname.endsWith('/index.html');if(isRoot&&!(await pushReady()))return (await caches.match('./activar-notificaciones.html'))||Response.error();return (await caches.match(req))||(await caches.match(isRoot?'./index.html':'./'))}})());return}event.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(req,copy));return r})))});